# Generated by Django 4.1 on 2022-08-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='digits',
        ),
    ]
