# Generated by Django 4.1 on 2022-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_remove_theater_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='digits',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='digits',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
