# Generated by Django 4.1 on 2022-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_theater_digits_alter_movie_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='digits',
            field=models.PositiveSmallIntegerField(default=2, unique=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='digits',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
