// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ6b-dvDNnlJm344nVodnmWYFoFojbhEY',
    appId: '1:863025956296:web:3bc7762e817c771ce26cfd',
    messagingSenderId: '863025956296',
    projectId: 'ivrs-8b2eb',
    authDomain: 'ivrs-8b2eb.firebaseapp.com',
    storageBucket: 'ivrs-8b2eb.appspot.com',
    measurementId: 'G-VL7RK7NDEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpeccc9UYBxxP3fz2TaoizWPDoCYHVKoA',
    appId: '1:863025956296:android:461c24f69d977664e26cfd',
    messagingSenderId: '863025956296',
    projectId: 'ivrs-8b2eb',
    storageBucket: 'ivrs-8b2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYu6NjftNfXHbiPP_fhk0tGYkZ-YvlsRU',
    appId: '1:863025956296:ios:980d30abe652e16fe26cfd',
    messagingSenderId: '863025956296',
    projectId: 'ivrs-8b2eb',
    storageBucket: 'ivrs-8b2eb.appspot.com',
    iosClientId: '863025956296-65rsup0egfcg2trpj90eqm87gvfd4j54.apps.googleusercontent.com',
    iosBundleId: 'com.ivr.ivrFrontend',
  );
}
